; normal - looking at a brighter hive slot
; altUI - looking at a darker hive slot (alternative camera rotation)
bitmaps["hive"] := Map()
bitmaps["hive"]["day"] := Gdip_CreateBitmap(22, 4), G := Gdip_GraphicsFromImage(bitmaps["hive"]["day"]), Gdip_GraphicsClear(G, 0xFFd28f0c), Gdip_DeleteGraphics(G)
bitmaps["hive"]["night"] := Gdip_CreateBitmap(22, 4), G := Gdip_GraphicsFromImage(bitmaps["hive"]["night"]), Gdip_GraphicsClear(G, 0xFFc08200), Gdip_DeleteGraphics(G)
bitmaps["hive"]["day-beesmas"] := Gdip_CreateBitmap(22, 4), G := Gdip_GraphicsFromImage(bitmaps["hive"]["day-beesmas"]), Gdip_GraphicsClear(G, 0xFFDB9502), Gdip_DeleteGraphics(G)
bitmaps["hive"]["day-beesmas-altUI"] := Gdip_CreateBitmap(22, 4), G := Gdip_GraphicsFromImage(bitmaps["hive"]["day-beesmas-altUI"]), Gdip_GraphicsClear(G, 0xFF9B6A01), Gdip_DeleteGraphics(G)
;bitmaps["hive"]["night-beesmas"] := Gdip_CreateBitmap(22, 4), G := Gdip_GraphicsFromImage(bitmaps["hive"]["night-beesmas"]), Gdip_GraphicsClear(G, 0xFF), Gdip_DeleteGraphics(G)
bitmaps["hive"]["day-altUI"] := Gdip_CreateBitmap(22, 4), G := Gdip_GraphicsFromImage(bitmaps["hive"]["day-altUI"]), Gdip_GraphicsClear(G, 0xFF916507), Gdip_DeleteGraphics(G)
bitmaps["hive"]["night-altUI"] := Gdip_CreateBitmap(22, 4), G := Gdip_GraphicsFromImage(bitmaps["hive"]["night-altUI"]), Gdip_GraphicsClear(G, 0xFF845c00), Gdip_DeleteGraphics(G)
bitmaps["hive"]["day-gifted"] := Gdip_CreateBitmap(22, 4), G := Gdip_GraphicsFromImage(bitmaps["hive"]["day-gifted"]), Gdip_GraphicsClear(G, 0xFFb97e03), Gdip_DeleteGraphics(G)
bitmaps["hive"]["night-gifted"] := Gdip_CreateBitmap(22, 4), G := Gdip_GraphicsFromImage(bitmaps["hive"]["night-gifted"]), Gdip_GraphicsClear(G, 0xFFaa7400), Gdip_DeleteGraphics(G)
bitmaps["hive"]["noshadow-day"] := Gdip_CreateBitmap(22, 4), G := Gdip_GraphicsFromImage(bitmaps["hive"]["noshadow-day"]), Gdip_GraphicsClear(G, 0xFFffb325), Gdip_DeleteGraphics(G)
bitmaps["hive"]["noshadow-night"] := Gdip_CreateBitmap(22, 4), G := Gdip_GraphicsFromImage(bitmaps["hive"]["noshadow-night"]), Gdip_GraphicsClear(G, 0xFF694a00), Gdip_DeleteGraphics(G)
bitmaps["hive"]["noshadow-gifted"] := Gdip_CreateBitmap(22, 4), G := Gdip_GraphicsFromImage(bitmaps["hive"]["noshadow-gifted"]), Gdip_GraphicsClear(G, 0xFFe39d1f), Gdip_DeleteGraphics(G)
bitmaps["hive"]["wing"] := Gdip_CreateBitmap(22, 4), G := Gdip_GraphicsFromImage(bitmaps["hive"]["wing"]), Gdip_GraphicsClear(G, 0xFFa28645), Gdip_DeleteGraphics(G)

bitmaps["spawn"] := Map()
bitmaps["spawn"]["day"] := Gdip_CreateBitmap(22, 4), G := Gdip_GraphicsFromImage(bitmaps["spawn"]["day"]), Gdip_GraphicsClear(G, 0xFF937B1F), Gdip_DeleteGraphics(G)
bitmaps["spawn"]["beesmas-day"] := Gdip_CreateBitmap(22, 4), G := Gdip_GraphicsFromImage(bitmaps["spawn"]["beesmas-day"]), Gdip_GraphicsClear(G, 0xFF98874D), Gdip_DeleteGraphics(G)
bitmaps["spawn"]["night"] := Gdip_CreateBitmap(22, 4), G := Gdip_GraphicsFromImage(bitmaps["spawn"]["night"]), Gdip_GraphicsClear(G, 0xFF796615), Gdip_DeleteGraphics(G)
bitmaps["spawn"]["beesmas-night"] := Gdip_CreateBitmap(22, 4), G := Gdip_GraphicsFromImage(bitmaps["spawn"]["beesmas-night"]), Gdip_GraphicsClear(G, 0xFF8B8769), Gdip_DeleteGraphics(G) ; foggy night
bitmaps["spawn"]["day-honey"] := Gdip_CreateBitmap(22, 4), G := Gdip_GraphicsFromImage(bitmaps["spawn"]["day-honey"]), Gdip_GraphicsClear(G, 0xFFC1AE55), Gdip_DeleteGraphics(G)
;bitmaps["spawn"]["beesmas-day-honey"] := Gdip_CreateBitmap(22, 4), G := Gdip_GraphicsFromImage(bitmaps["spawn"]["beesmas-day-honey"]), Gdip_GraphicsClear(G, 0xFF), Gdip_DeleteGraphics(G)
;bitmaps["spawn"]["night-honey"] := Gdip_CreateBitmap(22, 4), G := Gdip_GraphicsFromImage(bitmaps["spawn"]["night-honey"]), Gdip_GraphicsClear(G, 0xFF), Gdip_DeleteGraphics(G)
bitmaps["spawn"]["beesmas-night-honey"] := Gdip_CreateBitmap(22, 4), G := Gdip_GraphicsFromImage(bitmaps["spawn"]["beesmas-night-honey"]), Gdip_GraphicsClear(G, 0xFFC3B35D), Gdip_DeleteGraphics(G)
bitmaps["spawn"]["day-snow"] := Gdip_CreateBitmap(22, 4), G := Gdip_GraphicsFromImage(bitmaps["spawn"]["day-snow"]), Gdip_GraphicsClear(G, 0xFFC3BCA3), Gdip_DeleteGraphics(G)
;bitmaps["spawn"]["night-snow"] := Gdip_CreateBitmap(22, 4), G := Gdip_GraphicsFromImage(bitmaps["spawn"]["night-snow"]), Gdip_GraphicsClear(G, 0xFF), Gdip_DeleteGraphics(G)
bitmaps["spawn"]["day-meteor"] := Gdip_CreateBitmap(22, 4), G := Gdip_GraphicsFromImage(bitmaps["spawn"]["day-meteor"]), Gdip_GraphicsClear(G, 0xFF957A70), Gdip_DeleteGraphics(G)
bitmaps["spawn"]["beesmas-day-meteor"] := Gdip_CreateBitmap(22, 4), G := Gdip_GraphicsFromImage(bitmaps["spawn"]["beesmas-day-meteor"]), Gdip_GraphicsClear(G, 0xFF977B82), Gdip_DeleteGraphics(G)
;bitmaps["spawn"]["night-meteor"] := Gdip_CreateBitmap(22, 4), G := Gdip_GraphicsFromImage(bitmaps["spawn"]["night-meteor"]), Gdip_GraphicsClear(G, 0xFF), Gdip_DeleteGraphics(G)
;bitmaps["spawn"]["beesmas-night-meteor"] := Gdip_CreateBitmap(22, 4), G := Gdip_GraphicsFromImage(bitmaps["spawn"]["beesmas-night-meteor"]), Gdip_GraphicsClear(G, 0xFF), Gdip_DeleteGraphics(G)
